version: '3'

services:

  reverseProxyQa:
    container_name: 'reverseproxyqa'
    image: 'reverseproxyqa'
    restart: always
    build:
      context: ./reverseProxy
      dockerfile: Dockerfile.qa
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - acme-challenge-volume:/data/letsencrypt
      - letsencryptetc-volume:/etc/letsencrypt
      - dhparam-volume:/data/dhparam
    networks:
      - vrnoaf-network

  frontend:
    build:
      args:
        - WP_ENDPOINT=betawp\.vrnoaf\.no

volumes:
  acme-challenge-volume:
  letsencryptetc-volume:
  dhparam-volume:
  #For persisting data used in scripts
  letsencryptlib-volume:
  #For inspecting logs
  letsencryptlog-volume:
