version: '3'

services:

  reverseProxy:
    container_name: 'reverseproxy'
    image: 'reverseproxy'
    restart: always
    build:
      context: ./reverseProxy
      dockerfile: Dockerfile
    networks:
      - vrnoaf-network
    ports:
      - "80:80"

  frontend:
    build:
      args:
        - WP_ENDPOINT=http://wp.vrnoaf.no/wp-json/wp/v2/