version: '3'

services:

  frontend:
    container_name: 'frontend'
    restart: always
    networks:
      - vrnoaf-network
  
  wordpressdb:
    container_name: 'wordpressdb'
    image: mariadb:latest
    volumes:
      - wpdb-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariawunderbar
      - MYSQL_DATABASE=wordpress
    networks:
      - vrnoaf-network

  wordpress:
    container_name: 'wordpress'
    image: wordpress:latest
    restart: always
    links:
      - wordpressdb:mysql
    volumes:
      - wp-volume:/var/www/html
    environment:
      - WORDPRESS_DB_PASSWORD=mariawunderbar
    networks:
      - vrnoaf-network

volumes:
  wpdb-volume:
  wp-volume:

networks:
  vrnoaf-network:
    driver: bridge