version: '3'

services:

  frontend:
    ports:
      - "80:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - WP_ENDPOINT=xxxx:5050

  wordpress:
    ports:
      - "5050:80"