version: '3'

services:

  reverseProxy:
    container_name: 'reverseproxy'
    image: 'kristianw87/vrnoaf-reverseproxy:latest'
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - acme-challenge-volume:/data/letsencrypt
      - letsencryptetc-volume:/etc/letsencrypt
      - dhparam-volume:/data/dhparam
    networks:
      - vrnoaf-network
    depends_on:
      - frontend
      - wordpress

  frontend:
    image: 'kristianw87/vrnoaf-frontend:latest'
    #build:
    #  args:
    #    - WP_ENDPOINT=wp\.vrnoaf\.no

volumes:
  acme-challenge-volume:
  letsencryptetc-volume:
  dhparam-volume:
  #For persisting data used in scripts
  letsencryptlib-volume:
  #For inspecting logs
  letsencryptlog-volume:
