version: '3'

services:

  frontend:
    image: node:latest
    command: bash -c "cd /app && npm install && npm start"
    volumes:
        - node_modules:/app/node_modules
        - ./frontend:/app
    ports:
        - "4200:4200"

  wordpress:
    ports:
      - "5050:80"

volumes:
  node_modules: